### ISSUE TITLE
Implement the functionality to save CLO information

### ISSUE THREAD

**Issue by iFaisal** [sarahalgadi/Miqyas#50]

**Comment by iFaisal** [comment]
Related to user story #18

**Comment by iFaisal** [comment]
Related to user story #19

**Comment by sarahalgadi** [comment]
Not yet done due to no access to database or dummy data.

**Comment by iFaisal** [comment]
> Not yet done due to no access to database or dummy data.

Please choose between using Reem's database on your computer or crafting your own abstraction, and don't forget to use the data in google sheets if necessary.
